In [1]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot


In [4]:
### Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size --- numer of unique words in the context
voc_size=500

# One Hot Representation

In [7]:
onehot_repr=[one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[495, 199, 472, 414], [495, 199, 472, 362], [495, 161, 472, 422], [332, 272, 134, 467, 343], [332, 272, 134, 467, 402], [50, 495, 7, 472, 137], [170, 486, 449, 467]]


# Word Embedding Representations

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np


In [11]:
### Prepadding

sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 495 199 472 414]
 [  0   0   0   0 495 199 472 362]
 [  0   0   0   0 495 161 472 422]
 [  0   0   0 332 272 134 467 343]
 [  0   0   0 332 272 134 467 402]
 [  0   0   0  50 495   7 472 137]
 [  0   0   0   0 170 486 449 467]]


In [12]:
## 10 feature dimension
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
#### the glass of milk
embedded_docs[0]

array([  0,   0,   0,   0, 495, 199, 472, 414], dtype=int32)

In [17]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step


array([[ 0.03745217,  0.03130463,  0.04442874, -0.0148361 ,  0.03840883,
         0.00792079,  0.01290078,  0.0003034 ,  0.03851545,  0.0493752 ],
       [ 0.03745217,  0.03130463,  0.04442874, -0.0148361 ,  0.03840883,
         0.00792079,  0.01290078,  0.0003034 ,  0.03851545,  0.0493752 ],
       [ 0.03745217,  0.03130463,  0.04442874, -0.0148361 ,  0.03840883,
         0.00792079,  0.01290078,  0.0003034 ,  0.03851545,  0.0493752 ],
       [ 0.03745217,  0.03130463,  0.04442874, -0.0148361 ,  0.03840883,
         0.00792079,  0.01290078,  0.0003034 ,  0.03851545,  0.0493752 ],
       [-0.00011991,  0.03603155,  0.02574824,  0.0492929 ,  0.01804737,
         0.0048874 ,  0.03981272, -0.0292029 , -0.0387293 ,  0.01591961],
       [ 0.01508636,  0.04075145, -0.00213935, -0.03166791, -0.0264287 ,
         0.02739031,  0.02918785,  0.02688321, -0.02426795,  0.02780408],
       [-0.03922937, -0.04430225, -0.01137327,  0.04354136, -0.00609125,
        -0.02255509, -0.04651555,  0.04513406

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 495, 199, 472, 414], dtype=int32)

### Assignment

sent=[
      **"The world is a better place",**

      **"Marvel series is my favourite movie",**

      **"I like DC movies",**

      **"the cat is eating the food",**

      **"Tom and Jerry is my favourite movie",**

      **"Python is my favourite programming language"**
      ]

In [39]:
### rensorflow

from tensorflow.keras.preprocessing.text import one_hot

In [40]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [41]:
voc_size=500

In [42]:
onehot_rep=[one_hot(words, voc_size)for words in sent]
print(onehot_rep)

[[495, 290, 157, 134, 268, 250], [135, 187, 157, 163, 71, 466], [332, 17, 228, 155], [495, 24, 157, 19, 495, 153], [352, 286, 89, 157, 163, 71, 466], [8, 157, 163, 71, 401, 83]]


In [43]:
### Word Embeddings
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [44]:
import numpy as np

In [45]:
## Post Padding

sent_length=10
embedded_docs=pad_sequences(onehot_rep, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 495 290 157 134 268 250]
 [  0   0   0   0 135 187 157 163  71 466]
 [  0   0   0   0   0   0 332  17 228 155]
 [  0   0   0   0 495  24 157  19 495 153]
 [  0   0   0 352 286  89 157 163  71 466]
 [  0   0   0   0   8 157 163  71 401  83]]


In [46]:
## 15 feature dimensions

In [47]:
dim=10


In [48]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [49]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [50]:
embedded_docs[0]

array([  0,   0,   0,   0, 495, 290, 157, 134, 268, 250], dtype=int32)

In [51]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step
[[[ 9.05990601e-05 -4.69829813e-02  7.49323517e-03  2.11676098e-02
    4.81176488e-02 -6.74001127e-03  2.74649747e-02 -2.07807776e-02
   -2.89618131e-02  2.73843668e-02]
  [ 9.05990601e-05 -4.69829813e-02  7.49323517e-03  2.11676098e-02
    4.81176488e-02 -6.74001127e-03  2.74649747e-02 -2.07807776e-02
   -2.89618131e-02  2.73843668e-02]
  [ 9.05990601e-05 -4.69829813e-02  7.49323517e-03  2.11676098e-02
    4.81176488e-02 -6.74001127e-03  2.74649747e-02 -2.07807776e-02
   -2.89618131e-02  2.73843668e-02]
  [ 9.05990601e-05 -4.69829813e-02  7.49323517e-03  2.11676098e-02
    4.81176488e-02 -6.74001127e-03  2.74649747e-02 -2.07807776e-02
   -2.89618131e-02  2.73843668e-02]
  [-2.41837036e-02  2.23253705e-02  2.92595141e-02 -9.06367227e-03
    8.84079933e-03 -1.08555444e-02 -3.27599533e-02 -3.70052569e-02
   -1.52746551e-02  3.91770266e-02]
  [-4.81879003e-02  3.39356177e-02  4.56121452e-02 -1.35657415e-02
    3.13226841e-02 -4.23158891e-02  2.553545